(cl:defpackage rob599_hw1-msg
  (:use )
  (:export
   "<APPROACHACTION>"
   "APPROACHACTION"
   "<APPROACHACTIONFEEDBACK>"
   "APPROACHACTIONFEEDBACK"
   "<APPROACHACTIONGOAL>"
   "APPROACHACTIONGOAL"
   "<APPROACHACTIONRESULT>"
   "APPROACHACTIONRESULT"
   "<APPROACHFEEDBACK>"
   "APPROACHFEEDBACK"
   "<APPROACHGOAL>"
   "APPROACHGOAL"
   "<APPROACHRESULT>"
   "APPROACHRESULT"
  ))

