; Auto-generated. Do not edit!


(cl:in-package rob599_hw1-msg)


;//! \htmlinclude approachResult.msg.html

(cl:defclass <approachResult> (roslisp-msg-protocol:ros-message)
  ((goal_reached
    :reader goal_reached
    :initarg :goal_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass approachResult (<approachResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <approachResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'approachResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rob599_hw1-msg:<approachResult> is deprecated: use rob599_hw1-msg:approachResult instead.")))

(cl:ensure-generic-function 'goal_reached-val :lambda-list '(m))
(cl:defmethod goal_reached-val ((m <approachResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rob599_hw1-msg:goal_reached-val is deprecated.  Use rob599_hw1-msg:goal_reached instead.")
  (goal_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <approachResult>) ostream)
  "Serializes a message object of type '<approachResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'goal_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <approachResult>) istream)
  "Deserializes a message object of type '<approachResult>"
    (cl:setf (cl:slot-value msg 'goal_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<approachResult>)))
  "Returns string type for a message object of type '<approachResult>"
  "rob599_hw1/approachResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'approachResult)))
  "Returns string type for a message object of type 'approachResult"
  "rob599_hw1/approachResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<approachResult>)))
  "Returns md5sum for a message object of type '<approachResult>"
  "a65bc774d2139031955fd7cc94fdd40f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'approachResult)))
  "Returns md5sum for a message object of type 'approachResult"
  "a65bc774d2139031955fd7cc94fdd40f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<approachResult>)))
  "Returns full string definition for message of type '<approachResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool goal_reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'approachResult)))
  "Returns full string definition for message of type 'approachResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool goal_reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <approachResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <approachResult>))
  "Converts a ROS message object to a list"
  (cl:list 'approachResult
    (cl:cons ':goal_reached (goal_reached msg))
))
