; Auto-generated. Do not edit!


(cl:in-package rob599_hw1-msg)


;//! \htmlinclude approachGoal.msg.html

(cl:defclass <approachGoal> (roslisp-msg-protocol:ros-message)
  ((stopping_distance
    :reader stopping_distance
    :initarg :stopping_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass approachGoal (<approachGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <approachGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'approachGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rob599_hw1-msg:<approachGoal> is deprecated: use rob599_hw1-msg:approachGoal instead.")))

(cl:ensure-generic-function 'stopping_distance-val :lambda-list '(m))
(cl:defmethod stopping_distance-val ((m <approachGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rob599_hw1-msg:stopping_distance-val is deprecated.  Use rob599_hw1-msg:stopping_distance instead.")
  (stopping_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <approachGoal>) ostream)
  "Serializes a message object of type '<approachGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'stopping_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <approachGoal>) istream)
  "Deserializes a message object of type '<approachGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'stopping_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<approachGoal>)))
  "Returns string type for a message object of type '<approachGoal>"
  "rob599_hw1/approachGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'approachGoal)))
  "Returns string type for a message object of type 'approachGoal"
  "rob599_hw1/approachGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<approachGoal>)))
  "Returns md5sum for a message object of type '<approachGoal>"
  "91d6fae14032f66194a4a3424f9dee78")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'approachGoal)))
  "Returns md5sum for a message object of type 'approachGoal"
  "91d6fae14032f66194a4a3424f9dee78")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<approachGoal>)))
  "Returns full string definition for message of type '<approachGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 stopping_distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'approachGoal)))
  "Returns full string definition for message of type 'approachGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 stopping_distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <approachGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <approachGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'approachGoal
    (cl:cons ':stopping_distance (stopping_distance msg))
))
