// Auto-generated. Do not edit!

// (in-package rob599_hw1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class approachFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_to_obstacle = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_to_obstacle')) {
        this.distance_to_obstacle = initObj.distance_to_obstacle
      }
      else {
        this.distance_to_obstacle = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type approachFeedback
    // Serialize message field [distance_to_obstacle]
    bufferOffset = _serializer.float32(obj.distance_to_obstacle, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type approachFeedback
    let len;
    let data = new approachFeedback(null);
    // Deserialize message field [distance_to_obstacle]
    data.distance_to_obstacle = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rob599_hw1/approachFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b0895f7086961063ab269c461c489df4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 distance_to_obstacle
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new approachFeedback(null);
    if (msg.distance_to_obstacle !== undefined) {
      resolved.distance_to_obstacle = msg.distance_to_obstacle;
    }
    else {
      resolved.distance_to_obstacle = 0.0
    }

    return resolved;
    }
};

module.exports = approachFeedback;
