// Auto-generated. Do not edit!

// (in-package rob599_hw1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class approachGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.stopping_distance = null;
    }
    else {
      if (initObj.hasOwnProperty('stopping_distance')) {
        this.stopping_distance = initObj.stopping_distance
      }
      else {
        this.stopping_distance = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type approachGoal
    // Serialize message field [stopping_distance]
    bufferOffset = _serializer.float32(obj.stopping_distance, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type approachGoal
    let len;
    let data = new approachGoal(null);
    // Deserialize message field [stopping_distance]
    data.stopping_distance = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rob599_hw1/approachGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '91d6fae14032f66194a4a3424f9dee78';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 stopping_distance
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new approachGoal(null);
    if (msg.stopping_distance !== undefined) {
      resolved.stopping_distance = msg.stopping_distance;
    }
    else {
      resolved.stopping_distance = 0.0
    }

    return resolved;
    }
};

module.exports = approachGoal;
