// Generated by gencpp from file rob599_hw1/approachResult.msg
// DO NOT EDIT!


#ifndef ROB599_HW1_MESSAGE_APPROACHRESULT_H
#define ROB599_HW1_MESSAGE_APPROACHRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rob599_hw1
{
template <class ContainerAllocator>
struct approachResult_
{
  typedef approachResult_<ContainerAllocator> Type;

  approachResult_()
    : goal_reached(false)  {
    }
  approachResult_(const ContainerAllocator& _alloc)
    : goal_reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _goal_reached_type;
  _goal_reached_type goal_reached;





  typedef boost::shared_ptr< ::rob599_hw1::approachResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rob599_hw1::approachResult_<ContainerAllocator> const> ConstPtr;

}; // struct approachResult_

typedef ::rob599_hw1::approachResult_<std::allocator<void> > approachResult;

typedef boost::shared_ptr< ::rob599_hw1::approachResult > approachResultPtr;
typedef boost::shared_ptr< ::rob599_hw1::approachResult const> approachResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rob599_hw1::approachResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rob599_hw1::approachResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rob599_hw1::approachResult_<ContainerAllocator1> & lhs, const ::rob599_hw1::approachResult_<ContainerAllocator2> & rhs)
{
  return lhs.goal_reached == rhs.goal_reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rob599_hw1::approachResult_<ContainerAllocator1> & lhs, const ::rob599_hw1::approachResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rob599_hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rob599_hw1::approachResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob599_hw1::approachResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_hw1::approachResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_hw1::approachResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_hw1::approachResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_hw1::approachResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rob599_hw1::approachResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a65bc774d2139031955fd7cc94fdd40f";
  }

  static const char* value(const ::rob599_hw1::approachResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa65bc774d2139031ULL;
  static const uint64_t static_value2 = 0x955fd7cc94fdd40fULL;
};

template<class ContainerAllocator>
struct DataType< ::rob599_hw1::approachResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rob599_hw1/approachResult";
  }

  static const char* value(const ::rob599_hw1::approachResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rob599_hw1::approachResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool goal_reached\n"
;
  }

  static const char* value(const ::rob599_hw1::approachResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rob599_hw1::approachResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct approachResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rob599_hw1::approachResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rob599_hw1::approachResult_<ContainerAllocator>& v)
  {
    s << indent << "goal_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROB599_HW1_MESSAGE_APPROACHRESULT_H
