// Generated by gencpp from file rob599_hw1/stopping_distance.msg
// DO NOT EDIT!


#ifndef ROB599_HW1_MESSAGE_STOPPING_DISTANCE_H
#define ROB599_HW1_MESSAGE_STOPPING_DISTANCE_H

#include <ros/service_traits.h>


#include <rob599_hw1/stopping_distanceRequest.h>
#include <rob599_hw1/stopping_distanceResponse.h>


namespace rob599_hw1
{

struct stopping_distance
{

typedef stopping_distanceRequest Request;
typedef stopping_distanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stopping_distance
} // namespace rob599_hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rob599_hw1::stopping_distance > {
  static const char* value()
  {
    return "df4297412d514e842de4f3301701343a";
  }

  static const char* value(const ::rob599_hw1::stopping_distance&) { return value(); }
};

template<>
struct DataType< ::rob599_hw1::stopping_distance > {
  static const char* value()
  {
    return "rob599_hw1/stopping_distance";
  }

  static const char* value(const ::rob599_hw1::stopping_distance&) { return value(); }
};


// service_traits::MD5Sum< ::rob599_hw1::stopping_distanceRequest> should match
// service_traits::MD5Sum< ::rob599_hw1::stopping_distance >
template<>
struct MD5Sum< ::rob599_hw1::stopping_distanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rob599_hw1::stopping_distance >::value();
  }
  static const char* value(const ::rob599_hw1::stopping_distanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob599_hw1::stopping_distanceRequest> should match
// service_traits::DataType< ::rob599_hw1::stopping_distance >
template<>
struct DataType< ::rob599_hw1::stopping_distanceRequest>
{
  static const char* value()
  {
    return DataType< ::rob599_hw1::stopping_distance >::value();
  }
  static const char* value(const ::rob599_hw1::stopping_distanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rob599_hw1::stopping_distanceResponse> should match
// service_traits::MD5Sum< ::rob599_hw1::stopping_distance >
template<>
struct MD5Sum< ::rob599_hw1::stopping_distanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rob599_hw1::stopping_distance >::value();
  }
  static const char* value(const ::rob599_hw1::stopping_distanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob599_hw1::stopping_distanceResponse> should match
// service_traits::DataType< ::rob599_hw1::stopping_distance >
template<>
struct DataType< ::rob599_hw1::stopping_distanceResponse>
{
  static const char* value()
  {
    return DataType< ::rob599_hw1::stopping_distance >::value();
  }
  static const char* value(const ::rob599_hw1::stopping_distanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROB599_HW1_MESSAGE_STOPPING_DISTANCE_H
