; Auto-generated. Do not edit!


(cl:in-package rob599_basic-msg)


;//! \htmlinclude FibonacciFeedback.msg.html

(cl:defclass <FibonacciFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:integer
    :initform 0))
)

(cl:defclass FibonacciFeedback (<FibonacciFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FibonacciFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FibonacciFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rob599_basic-msg:<FibonacciFeedback> is deprecated: use rob599_basic-msg:FibonacciFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <FibonacciFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rob599_basic-msg:progress-val is deprecated.  Use rob599_basic-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FibonacciFeedback>) ostream)
  "Serializes a message object of type '<FibonacciFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'progress)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FibonacciFeedback>) istream)
  "Deserializes a message object of type '<FibonacciFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'progress) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FibonacciFeedback>)))
  "Returns string type for a message object of type '<FibonacciFeedback>"
  "rob599_basic/FibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FibonacciFeedback)))
  "Returns string type for a message object of type 'FibonacciFeedback"
  "rob599_basic/FibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FibonacciFeedback>)))
  "Returns md5sum for a message object of type '<FibonacciFeedback>"
  "880606345f35c22a654c3c928cd368c0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FibonacciFeedback)))
  "Returns md5sum for a message object of type 'FibonacciFeedback"
  "880606345f35c22a654c3c928cd368c0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FibonacciFeedback>)))
  "Returns full string definition for message of type '<FibonacciFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int64 progress~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FibonacciFeedback)))
  "Returns full string definition for message of type 'FibonacciFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%int64 progress~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FibonacciFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FibonacciFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FibonacciFeedback
    (cl:cons ':progress (progress msg))
))
