// Generated by gencpp from file rob599_basic/Doubler.msg
// DO NOT EDIT!


#ifndef ROB599_BASIC_MESSAGE_DOUBLER_H
#define ROB599_BASIC_MESSAGE_DOUBLER_H

#include <ros/service_traits.h>


#include <rob599_basic/DoublerRequest.h>
#include <rob599_basic/DoublerResponse.h>


namespace rob599_basic
{

struct Doubler
{

typedef DoublerRequest Request;
typedef DoublerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Doubler
} // namespace rob599_basic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rob599_basic::Doubler > {
  static const char* value()
  {
    return "cd11c21fe194ec0173733fddd2cd457b";
  }

  static const char* value(const ::rob599_basic::Doubler&) { return value(); }
};

template<>
struct DataType< ::rob599_basic::Doubler > {
  static const char* value()
  {
    return "rob599_basic/Doubler";
  }

  static const char* value(const ::rob599_basic::Doubler&) { return value(); }
};


// service_traits::MD5Sum< ::rob599_basic::DoublerRequest> should match
// service_traits::MD5Sum< ::rob599_basic::Doubler >
template<>
struct MD5Sum< ::rob599_basic::DoublerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rob599_basic::Doubler >::value();
  }
  static const char* value(const ::rob599_basic::DoublerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob599_basic::DoublerRequest> should match
// service_traits::DataType< ::rob599_basic::Doubler >
template<>
struct DataType< ::rob599_basic::DoublerRequest>
{
  static const char* value()
  {
    return DataType< ::rob599_basic::Doubler >::value();
  }
  static const char* value(const ::rob599_basic::DoublerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rob599_basic::DoublerResponse> should match
// service_traits::MD5Sum< ::rob599_basic::Doubler >
template<>
struct MD5Sum< ::rob599_basic::DoublerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rob599_basic::Doubler >::value();
  }
  static const char* value(const ::rob599_basic::DoublerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob599_basic::DoublerResponse> should match
// service_traits::DataType< ::rob599_basic::Doubler >
template<>
struct DataType< ::rob599_basic::DoublerResponse>
{
  static const char* value()
  {
    return DataType< ::rob599_basic::Doubler >::value();
  }
  static const char* value(const ::rob599_basic::DoublerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROB599_BASIC_MESSAGE_DOUBLER_H
