// Generated by gencpp from file rob599_basic/DoublerResponse.msg
// DO NOT EDIT!


#ifndef ROB599_BASIC_MESSAGE_DOUBLERRESPONSE_H
#define ROB599_BASIC_MESSAGE_DOUBLERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rob599_basic
{
template <class ContainerAllocator>
struct DoublerResponse_
{
  typedef DoublerResponse_<ContainerAllocator> Type;

  DoublerResponse_()
    : doubled(0)  {
    }
  DoublerResponse_(const ContainerAllocator& _alloc)
    : doubled(0)  {
  (void)_alloc;
    }



   typedef int64_t _doubled_type;
  _doubled_type doubled;





  typedef boost::shared_ptr< ::rob599_basic::DoublerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rob599_basic::DoublerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DoublerResponse_

typedef ::rob599_basic::DoublerResponse_<std::allocator<void> > DoublerResponse;

typedef boost::shared_ptr< ::rob599_basic::DoublerResponse > DoublerResponsePtr;
typedef boost::shared_ptr< ::rob599_basic::DoublerResponse const> DoublerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rob599_basic::DoublerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rob599_basic::DoublerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rob599_basic::DoublerResponse_<ContainerAllocator1> & lhs, const ::rob599_basic::DoublerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.doubled == rhs.doubled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rob599_basic::DoublerResponse_<ContainerAllocator1> & lhs, const ::rob599_basic::DoublerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rob599_basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::DoublerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::DoublerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::DoublerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff7f570e39c1297ac8f5722d035ee11c";
  }

  static const char* value(const ::rob599_basic::DoublerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff7f570e39c1297aULL;
  static const uint64_t static_value2 = 0xc8f5722d035ee11cULL;
};

template<class ContainerAllocator>
struct DataType< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rob599_basic/DoublerResponse";
  }

  static const char* value(const ::rob599_basic::DoublerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# outputs\n"
"int64 doubled\n"
;
  }

  static const char* value(const ::rob599_basic::DoublerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.doubled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoublerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rob599_basic::DoublerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rob599_basic::DoublerResponse_<ContainerAllocator>& v)
  {
    s << indent << "doubled: ";
    Printer<int64_t>::stream(s, indent + "  ", v.doubled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROB599_BASIC_MESSAGE_DOUBLERRESPONSE_H
