// Generated by gencpp from file rob599_basic/FibonacciResult.msg
// DO NOT EDIT!


#ifndef ROB599_BASIC_MESSAGE_FIBONACCIRESULT_H
#define ROB599_BASIC_MESSAGE_FIBONACCIRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rob599_basic
{
template <class ContainerAllocator>
struct FibonacciResult_
{
  typedef FibonacciResult_<ContainerAllocator> Type;

  FibonacciResult_()
    : sequence()  {
    }
  FibonacciResult_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::rob599_basic::FibonacciResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rob599_basic::FibonacciResult_<ContainerAllocator> const> ConstPtr;

}; // struct FibonacciResult_

typedef ::rob599_basic::FibonacciResult_<std::allocator<void> > FibonacciResult;

typedef boost::shared_ptr< ::rob599_basic::FibonacciResult > FibonacciResultPtr;
typedef boost::shared_ptr< ::rob599_basic::FibonacciResult const> FibonacciResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rob599_basic::FibonacciResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rob599_basic::FibonacciResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rob599_basic::FibonacciResult_<ContainerAllocator1> & lhs, const ::rob599_basic::FibonacciResult_<ContainerAllocator2> & rhs)
{
  return lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rob599_basic::FibonacciResult_<ContainerAllocator1> & lhs, const ::rob599_basic::FibonacciResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rob599_basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::FibonacciResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::FibonacciResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::FibonacciResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43834c71ae4b726371cabcee1e961700";
  }

  static const char* value(const ::rob599_basic::FibonacciResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43834c71ae4b7263ULL;
  static const uint64_t static_value2 = 0x71cabcee1e961700ULL;
};

template<class ContainerAllocator>
struct DataType< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rob599_basic/FibonacciResult";
  }

  static const char* value(const ::rob599_basic::FibonacciResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"int64[] sequence\n"
;
  }

  static const char* value(const ::rob599_basic::FibonacciResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FibonacciResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rob599_basic::FibonacciResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rob599_basic::FibonacciResult_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROB599_BASIC_MESSAGE_FIBONACCIRESULT_H
