// Generated by gencpp from file rob599_basic/Rectangle.msg
// DO NOT EDIT!


#ifndef ROB599_BASIC_MESSAGE_RECTANGLE_H
#define ROB599_BASIC_MESSAGE_RECTANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rob599_basic
{
template <class ContainerAllocator>
struct Rectangle_
{
  typedef Rectangle_<ContainerAllocator> Type;

  Rectangle_()
    : height(0)
    , width(0)  {
    }
  Rectangle_(const ContainerAllocator& _alloc)
    : height(0)
    , width(0)  {
  (void)_alloc;
    }



   typedef int64_t _height_type;
  _height_type height;

   typedef int64_t _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::rob599_basic::Rectangle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rob599_basic::Rectangle_<ContainerAllocator> const> ConstPtr;

}; // struct Rectangle_

typedef ::rob599_basic::Rectangle_<std::allocator<void> > Rectangle;

typedef boost::shared_ptr< ::rob599_basic::Rectangle > RectanglePtr;
typedef boost::shared_ptr< ::rob599_basic::Rectangle const> RectangleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rob599_basic::Rectangle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rob599_basic::Rectangle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rob599_basic::Rectangle_<ContainerAllocator1> & lhs, const ::rob599_basic::Rectangle_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rob599_basic::Rectangle_<ContainerAllocator1> & lhs, const ::rob599_basic::Rectangle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rob599_basic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::Rectangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob599_basic::Rectangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::Rectangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob599_basic::Rectangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::Rectangle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob599_basic::Rectangle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rob599_basic::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2cea01c6068f229f4d26f3c1c2bd39c";
  }

  static const char* value(const ::rob599_basic::Rectangle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2cea01c6068f229ULL;
  static const uint64_t static_value2 = 0xf4d26f3c1c2bd39cULL;
};

template<class ContainerAllocator>
struct DataType< ::rob599_basic::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rob599_basic/Rectangle";
  }

  static const char* value(const ::rob599_basic::Rectangle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rob599_basic::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 height\n"
"int64 width\n"
;
  }

  static const char* value(const ::rob599_basic::Rectangle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rob599_basic::Rectangle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rectangle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rob599_basic::Rectangle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rob599_basic::Rectangle_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int64_t>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROB599_BASIC_MESSAGE_RECTANGLE_H
